import java.time.LocalDate
import java.time.format.DateTimeFormatter

plugins {
    java
}

defaultTasks("dist")

// The TWS jar files (for example C:\Jts\1051\jars) are needed so the compiler can
// resolve the TWS and Gateway entry points. Any TWS version will do. Set the
// IBC_BIN environment variable, or pass -PibcBin=<dir>.
val ibcBin: String? = providers.gradleProperty("ibcBin")
    .orElse(providers.environmentVariable("IBC_BIN"))
    .orNull

dependencies {
    if (ibcBin != null) compileOnly(fileTree(ibcBin) { include("**/*.jar") })
}

// The version is the build date, yy.M.d (eg 26.10.1), unless -PibcVersion=<version> is
// given (eg for a second release on the same day). A ValueSource is used so that the
// configuration cache notices when the date changes.
abstract class BuildDateVersion : ValueSource<String, ValueSourceParameters.None> {
    override fun obtain(): String =
        LocalDate.now().format(DateTimeFormatter.ofPattern("yy.M.d"))
}
val ibcVersion: String = providers.gradleProperty("ibcVersion")
    .orElse(providers.of(BuildDateVersion::class) {})
    .get()
version = ibcVersion

// Generate IbcVersionInfo from the version
val generateVersionInfo = tasks.register("generateVersionInfo") {
    val outDir = layout.buildDirectory.dir("generated/sources/version")
    inputs.property("version", ibcVersion)
    outputs.dir(outDir)
    val ver = ibcVersion
    doLast {
        val file = outDir.get().file("ibcalpha/ibc/IbcVersionInfo.java").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// NB: this file is generated by the Gradle build
            |
            |package ibcalpha.ibc;
            |
            |public class IbcVersionInfo {
            |    public final static String IBC_VERSION = "$ver";
            |}
            |""".trimMargin())
    }
}

sourceSets {
    main {
        java.srcDir(generateVersionInfo)
    }
}

tasks.compileJava {
    val ibcBinMissing = ibcBin == null
    doFirst {
        if (ibcBinMissing) throw GradleException(
            "Environment variable 'IBC_BIN' not set (set it to the fully-qualified directory " +
            "name containing the TWS jar files, or pass -PibcBin=<dir>).")
    }
    options.release = 17
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xlint:all")
}

tasks.jar {
    archiveFileName = "IBC.jar"
}

// The Windows distribution: IBC.jar, the files in src/main/dist and the licence.
// The version is stamped into ibc.ps1 ('ibc.ps1 version').
val dist = tasks.register<Zip>("dist") {
    group = "distribution"
    description = "Builds IBC.jar and the Windows distribution ZIP."
    archiveFileName = "IBC-$ibcVersion-windows.zip"
    destinationDirectory = layout.buildDirectory.dir("dist")
    inputs.property("ibcVersion", ibcVersion)
    from(tasks.jar)
    from("LICENSE.txt")
    from("src/main/dist") {
        val tokens = mapOf("IBC_VERSION" to ibcVersion)
        filesMatching("ibc.ps1") {
            filter<org.apache.tools.ant.filters.ReplaceTokens>("tokens" to tokens)
        }
    }
}

tasks.assemble { dependsOn(dist) }
