plugins {
    java
}

defaultTasks("dist")

// The TWS jar files (for example C:\Jts\1051\jars) are needed so the compiler can
// resolve the TWS and Gateway entry points. Any TWS version will do. Set the
// IBC_BIN environment variable, or pass -PibcBin=<dir>.
val ibcBin: String? = providers.gradleProperty("ibcBin")
    .orElse(providers.environmentVariable("IBC_BIN"))
    .orNull

dependencies {
    if (ibcBin != null) compileOnly(fileTree(ibcBin) { include("**/*.jar") })
}

// Generate IbcVersionInfo from the version in gradle.properties
val generateVersionInfo = tasks.register("generateVersionInfo") {
    val ver = project.version.toString()
    val outDir = layout.buildDirectory.dir("generated/sources/version")
    inputs.property("version", ver)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("ibcalpha/ibc/IbcVersionInfo.java").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// NB: this file is generated by the Gradle build
            |
            |package ibcalpha.ibc;
            |
            |public class IbcVersionInfo {
            |    public final static String IBC_VERSION = "$ver";
            |}
            |""".trimMargin())
    }
}

sourceSets {
    main {
        java.setSrcDirs(listOf("src"))
        java.srcDir(generateVersionInfo)
        resources.setSrcDirs(emptyList<String>())
    }
}

tasks.compileJava {
    val ibcBinMissing = ibcBin == null
    doFirst {
        if (ibcBinMissing) throw GradleException(
            "Environment variable 'IBC_BIN' not set (set it to the fully-qualified directory " +
            "name containing the TWS jar files, or pass -PibcBin=<dir>).")
    }
    options.release = 17
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xlint:all")
}

tasks.jar {
    archiveFileName = "IBC.jar"
}

// The distribution ZIPs contain the files in resources/, so keep the committed
// resources/IBC.jar and resources/version up to date, as the Ant build did
val updateResources = tasks.register<Copy>("updateResources") {
    description = "Copies IBC.jar into resources/ and writes resources/version."
    val ver = project.version.toString()
    val versionFile = layout.projectDirectory.file("resources/version")
    inputs.property("version", ver)
    outputs.file(versionFile)
    from(tasks.jar)
    into(layout.projectDirectory.dir("resources"))
    doLast {
        versionFile.asFile.writeText(ver)
    }
}

fun registerDistZip(platform: String, configure: CopySpec.() -> Unit) =
    tasks.register<Zip>("dist$platform") {
        group = "distribution"
        description = "Builds the $platform distribution ZIP."
        dependsOn(updateResources)
        archiveFileName = "IBC$platform-${project.version}.zip"
        destinationDirectory = layout.buildDirectory.dir("dist")
        from("LICENSE.txt")
        from("resources") {
            configure()
            filesMatching("**/*.sh") {
                permissions { unix("rwxr-xr-x") }
            }
        }
    }

val distWin = registerDistZip("Win") {
    exclude("**/*.sh", "**/*.plist")
}

val distLinux = registerDistZip("Linux") {
    exclude("**/*.bat", "**/*.vbs", "**/*macos.sh", "**/*.xml", "**/IBC (*", "**/*.plist", "**/*.ps1")
}

val distMacos = registerDistZip("Macos") {
    exclude("**/*.bat", "**/*.vbs", "**/*.xml", "**/IBC (*", "**/*.ps1")
    // the Linux start scripts; the macOS ones are twsstartmacos.sh and gatewaystartmacos.sh
    exclude("twsstart.sh", "gatewaystart.sh")
}

tasks.register("dist") {
    group = "distribution"
    description = "Builds IBC.jar and the Windows, Linux and macOS distribution ZIPs."
    dependsOn(distWin, distLinux, distMacos)
}
